apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: envManualEnvApprovalWorkflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
jobs:
  first-env-approval-job:
    environment: approval_QA
    steps:
      - name: Placeholder step
        uses: cloudbees-io/checkout@v1
  second-env-approval-job:
    environment: approval_QA
    steps:
      - name: Placeholder step
        uses: cloudbees-io/checkout@v1`
    needs:
      - first-env-approval-job
