apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: staged_release
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
metadata:
  stages/v1alpha1:
    - name: QA
      jobs:
        - print-deploy-to-qa
        - sleep-30
        - deploy_app
jobs:
  print-deploy-to-qa:
    steps:
      - run: echo "Deploying to qa-env"
        uses: docker://golang:1.20.3-alpine3.17
        name: Print Deploy
        shell: sh
  deploy_app:
    needs: sleep-30
    steps:
      - uses: test-cdro-qa/qa-python-hello-world/.cloudbees/workflows/deploy.yaml
        name: deploy
  sleep-30:
    needs: print-deploy-to-qa
    steps:
      - run: sleep 30
        uses: docker://golang:1.20.3-alpine3.17
        name: sleep job
        shell: sh
